 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/problem_infos", type: :request do
  
  # ProblemInfo. As you add validations to ProblemInfo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProblemInfo.create! valid_attributes
      get problem_infos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      problem_info = ProblemInfo.create! valid_attributes
      get problem_info_url(problem_info)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_problem_info_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      problem_info = ProblemInfo.create! valid_attributes
      get edit_problem_info_url(problem_info)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProblemInfo" do
        expect {
          post problem_infos_url, params: { problem_info: valid_attributes }
        }.to change(ProblemInfo, :count).by(1)
      end

      it "redirects to the created problem_info" do
        post problem_infos_url, params: { problem_info: valid_attributes }
        expect(response).to redirect_to(problem_info_url(ProblemInfo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProblemInfo" do
        expect {
          post problem_infos_url, params: { problem_info: invalid_attributes }
        }.to change(ProblemInfo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post problem_infos_url, params: { problem_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested problem_info" do
        problem_info = ProblemInfo.create! valid_attributes
        patch problem_info_url(problem_info), params: { problem_info: new_attributes }
        problem_info.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the problem_info" do
        problem_info = ProblemInfo.create! valid_attributes
        patch problem_info_url(problem_info), params: { problem_info: new_attributes }
        problem_info.reload
        expect(response).to redirect_to(problem_info_url(problem_info))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        problem_info = ProblemInfo.create! valid_attributes
        patch problem_info_url(problem_info), params: { problem_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested problem_info" do
      problem_info = ProblemInfo.create! valid_attributes
      expect {
        delete problem_info_url(problem_info)
      }.to change(ProblemInfo, :count).by(-1)
    end

    it "redirects to the problem_infos list" do
      problem_info = ProblemInfo.create! valid_attributes
      delete problem_info_url(problem_info)
      expect(response).to redirect_to(problem_infos_url)
    end
  end
end
